# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghsync" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "c503888653479dc7b5b120242a00135d58fa6f63f2966e4e43389b9ef984b19f"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "965cd76284a272588aeb41cf732a4d37dfa6f062baac546e038d47013f085d2a"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "719827503d23beb0b8165847cdc97b3b58ed81b56b2ad81cc042397ea655eba5"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "cde7d466573796810f82a0320716ad6fce1259b63132c3f48883ab0803332108"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghsync"
  desc "Clone, update and back up every repo of GitHub accounts."
  homepage "https://github.com/samykabu/ghsync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "ghsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghsync"]
    end
  end

  # No zap stanza required
end
