# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghsync" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "cc6d5e6156ff676223b6eb88864da26f58f79038e28b845eef049e12ad5ade20"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "4883814073a5791e68cdd9150a736742dcde5a61882e3ed6ff0464f83b3f1770"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "19956d2c7f193c1e5f607c19804d8bc8f7c8ac434a3329ba0e625fda0b6ac206"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "c662ee7aa6bd76de269604d80f20f37c6dfb44000c83df97e5a72a531127d4b5"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghsync"
  desc "Clone, update and back up every repo of GitHub accounts."
  homepage "https://github.com/samykabu/ghsync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "ghsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghsync"]
    end
  end

  # No zap stanza required
end
