# This file was generated by GoReleaser. DO NOT EDIT.
cask "ghsync" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "45c40f8acfcf31a68c9a858f27d4e85e64b62493917d1c47142ff64226ea8735"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b0f1a5350dcb6df25ba39fb7bf7ff673f481f5a85112dff0417dae58611b74b"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "bd49327d9e2f4fc85a85792caee7fbdb3db40c2f3394c2f2e6d035303a8d2732"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ec954a8b5ebc9a0d04eef9d0192b3429b5952b34703fabcc2e3393cad9221ee"
      url "https://github.com/samykabu/ghsync/releases/download/v#{version}/ghsync_#{version}_linux_amd64.tar.gz"
    end
  end

  name "ghsync"
  desc "Clone, update and back up every repo of GitHub accounts."
  homepage "https://github.com/samykabu/ghsync"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "git",
    ]

  binary "ghsync"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ghsync"]
    end
  end

  # No zap stanza required
end
